# Generated by Django 2.2 on 2019-06-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_perfil_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='photo',
            field=models.ImageField(blank=True, default='media/default_photo.png', upload_to='media/profile_photo'),
        ),
    ]
