# Generated by Django 2.2 on 2019-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_auto_20190628_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='photo',
            field=models.ImageField(blank=True, default='static/img/photo.png', upload_to='profile_photo'),
        ),
    ]
