# Generated by Django 2.2 on 2019-07-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_auto_20190629_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='photo',
            field=models.ImageField(blank=True, default='default_photo.png', upload_to='profile_photo'),
        ),
    ]
