# Generated by Django 2.2 on 2019-07-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0010_auto_20190715_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='posts_fotos'),
        ),
    ]
