# Generated by Django 2.2 on 2019-07-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0011_auto_20190715_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='perfis_bloqueados',
            field=models.ManyToManyField(related_name='contatos_bloqueados', to='perfis.Perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='contatos',
            field=models.ManyToManyField(related_name='perfil_meus_contatos', to='perfis.Perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='photo',
            field=models.ImageField(blank=True, default='%(class)s_default_photo.png', upload_to='profile_photo'),
        ),
    ]
